create schema if not exists skillio;

create table if not exists skillio.learning_categories (
  id text primary key,
  title text not null,
  subtitle text,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists skillio.user_learning_state (
  user_id uuid not null,
  category_id text not null,
  state_payload jsonb not null default '{}'::jsonb,
  xp integer not null default 0,
  mastery integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (user_id, category_id)
);

create table if not exists skillio.learning_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  category_id text not null,
  event_type text not null,
  event_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

grant usage on schema skillio to anon, authenticated;
grant select on skillio.learning_categories to anon, authenticated;
grant select, insert, update on skillio.user_learning_state to authenticated;
grant select, insert on skillio.learning_events to authenticated;

alter table skillio.learning_categories enable row level security;
alter table skillio.user_learning_state enable row level security;
alter table skillio.learning_events enable row level security;

drop policy if exists "read categories" on skillio.learning_categories;
create policy "read categories" on skillio.learning_categories for select using (true);

drop policy if exists "read own state" on skillio.user_learning_state;
create policy "read own state" on skillio.user_learning_state for select using (auth.uid() = user_id);

drop policy if exists "insert own state" on skillio.user_learning_state;
create policy "insert own state" on skillio.user_learning_state for insert with check (auth.uid() = user_id);

drop policy if exists "update own state" on skillio.user_learning_state;
create policy "update own state" on skillio.user_learning_state for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "read own events" on skillio.learning_events;
create policy "read own events" on skillio.learning_events for select using (auth.uid() = user_id);

drop policy if exists "insert own events" on skillio.learning_events;
create policy "insert own events" on skillio.learning_events for insert with check (auth.uid() = user_id);

insert into skillio.learning_categories (id,title,subtitle,status)
values
  ('skillio-app','Skillio App State','Gesamter Lernstand über alle Module','active'),
  ('change-management','Change Management','Business Transformation, Adoption und Data-Mesh-Transfer','active'),
  ('bullshit-bingo','Bullshit Bingo','IT- und Management-Buzzwords entlarven','active')
on conflict (id) do update set title=excluded.title, subtitle=excluded.subtitle, status=excluded.status, updated_at=now();
